version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: physact_db

  backend:
#    image: easyfitorg/physact_backend:latest
    build: ../backend/
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always
    container_name: physact_backend

  frontend:
      image: easyfitorg/physact_frontend:latest
      volumes:
        - node_build:/app/build/
      depends_on:
        - db
      tty: true
      stdin_open: true
      restart: always
      container_name: physact_frontend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - node_build:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend
    restart: always
    container_name: physact_nginx

volumes:
  postgres_data:
  static_value:
  media_value:
  node_build: