openapi: 3.0.2
info:
  title: 'Приложение для физической активности'
  version: '0.1'

servers:
  - url: http://127.0.0.1:8000/api/v1/
    description: 'Dev server' 

tags:
  - name: Пользователи
    description: 'Регистрация пользователей и выдача токенов'
  - name: Тренировки
    description: 'Получение и управление тренировками'
    
paths:

  /auth/signup/:
    post:
      operationId: Регистрация нового пользователя
      description: 'Регистрация нового пользователя'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomUserCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomUserResponseOnCreate'
          description: 'Пользователь успешно создан'
        '400':
          $ref: '#/components/responses/ValidationError'
      tags:
        - Пользователи
  
  /auth/activation/{uid}/{token}/:
    post:
      operationId: Активация нового пользователя
      description: 'Активация нового пользователя'
      parameters:
        - name: uid
          in: path
          required: true
          description: 'Идентификатор отправленный в ссылке в письме'
          schema:
            type: string
        - name: token
          in: path
          required: true
          description: 'Токен пользователя отправленный в ссылке в письме'
          schema:
            type: string
      responses:
        '204':
          description: 'Пользователь успешно активирован'
        '400':
          $ref: '#/components/responses/ActivationError'
        '403':
          $ref: '#/components/responses/PermissionDenied'
      tags:
        - Пользователи    

  /auth/token/login/:
    post:
      operationId: Получить токен авторизации
      description: 'Используется для авторизации по емейлу и паролю, чтобы далее использовать токен при запросах'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenGetResponse'
          description: ''
      tags:
        - Пользователи
        
  /auth/token/logout/:
    post:
      security:
        - Token: [ ]
      operationId: Удаление токена
      description: 'Удаляет токен текущего пользователя'
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        '204':
          content:
            application/json:
              schema: {}
          description: ''
        '401':
          $ref: '#/components/responses/AuthenticationError'
      tags:
        - Пользователи
  
  /auth/reset_password/:
    post:
      operationId: Сброс пароля
      description: 'Отправляет письмо со ссылкой для установки нового пароля'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  $ref: '#/components/schemas/Email'
      responses:
        '200':
          description: 'Письмо со ссылкой отправлено'
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    example: 'Письмо отправлено'
                    type: string
      tags:
        - Пользователи
        
  /auth/set_new_password/{uid}/{token}/:
    post:
      operationId: Установка нового пароля
      description: 'Устанавливает новый пароль'
      parameters:
        - name: uid
          in: path
          required: true
          description: 'Идентификатор отправленный в ссылке в письме'
          schema:
            type: string
        - name: token
          in: path
          required: true
          description: 'Токен пользователя отправленный в ссылке в письме'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                new_password:
                  $ref: '#/components/schemas/Password'
      responses:
        '200':
          description: 'Пароль изменен'
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    example: 'Пароль изменен'
                    type: string
        '401':
          $ref: '#/components/responses/AuthenticationError'
      tags:
        - Пользователи
        
  /users/{id}/:
    get:
      operationId: Профиль пользователя
      description: 'Получение данных пользователя, доступно авторизированному пользователю'
      security:
        - Token: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: "Уникальный id этого пользователя"
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/AuthenticationError'
      tags:
        - Пользователи
    patch:
      operationId: Профиль пользователя
      description: 'Изменение данных пользователя, доступно авторизированному пользователю'
      security:
        - Token: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: "Уникальный id этого пользователя"
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
        '404':
          $ref: '#/components/responses/NotFound'
        '401':
          $ref: '#/components/responses/AuthenticationError'
      tags:
        - Пользователи

  /trainings/:
    get:
      operationId: Список тренировок пользователя
      description: 'Список тренировок пользователя, доступно авторизированному пользователю. Доступна пагинация, отбор по периоду'
      security:
        - Token: [ ]
      parameters:
        - name: page
          required: false
          in: query
          description: 'Номер страницы'
          schema:
            type: integer
        - name: limit
          required: false
          in: query
          description: 'Количество объектов на странице'
          schema:
            type: integer
        - name: from_datetime
          required: false
          in: query
          description: 'Начало периода'
          schema:
            type: string
            format: '2023-07-04T00:05:23+03:00'
        - name: till_datetime
          required: false
          in: query
          description: 'Конец периода'
          schema:
            type: string
            format: '2023-07-04T00:05:23+03:00'
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                    example: 123
                    description: 'Общее количество объектов в базе'
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: 'http://127.0.0.1:8000/api/v1/trainings/?page=4'
                    description: 'Ссылка на следующую страницу'
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: 'http://127.0.0.1:8000/api/v1/trainings/?page=4'
                    description: 'Ссылка на предыдущую страницу'
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Training'
                    description: 'Список объектов текущей страницы'
          description: ''
        '401':
          $ref: '#/components/schemas/AuthenticationError'
      tags:
        - Тренировки
    post:
      operationId: Создание тренировки пользователя
      description: 'Доступно авторизированному пользователю'
      security:
        - Token: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TrainingCreate'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          description: 'Тренировка успешно создана'
        '400':
          description: 'Ошибки валидации в стандартном формате DRF'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          $ref: '#/components/responses/AuthenticationError'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Тренировки
  
  /trainings/{id}/:
    get:
      operationId: Получение данных тренировки
      description: 'Получение данных тренировки, доступно только автору тренировки'
      security:
        - Token: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: 'Уникальный идентификатор тренировки'
          schema:
            type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          description: ''
        '401':
          $ref: '#/components/responses/AuthenticationError'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Тренировки
    patch:
      operationId: Изменение данных тренировки
      description: 'Изменение данных тренировки, доступно только автору тренировки'
      security:
        - Token: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: 'Уникальный идентификатор тренировки'
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Training'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Training'
          description: 'Тренировка успешно обновлена'
        '400':
          description: 'Ошибки валидации в стандартном формате DRF'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          $ref: '#/components/responses/AuthenticationError'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Тренировки
    delete:
      operationId: Удаление тренировки
      description: 'Удаление тренировки, доступно только автору тренировки'
      security:
        - Token: [ ]
      parameters:
        - name: id
          in: path
          required: true
          description: 'Уникальный идентификатор тренировки'
          schema:
            type: string
      responses:
        '204':
          description: 'Тренировка успешно удалена'
        '401':
          $ref: '#/components/responses/AuthenticationError'
        '403':
          $ref: '#/components/responses/PermissionDenied'
        '404':
          $ref: '#/components/responses/NotFound'
      tags:
        - Тренировки
          
components:
  schemas:
  
    Name:
      type: string
      maxLength: 100
      description: 'Имя'
      example: 'Иван'
    Surname:
      type: string
      maxLength: 100
      description: 'Фамилия'
      example: 'Иванов'
    Phone:
      type: string
      maxLength: 20
      description: 'Номер телефона'
      pattern: \+?[0-9\s\-\(\)]+
      example: '+7(999)001-01-01'
    Email:
      type: string
      format: email
      maxLength: 100
      description: 'Адрес электронной почты'
      example: 'ivanov@yandex.ru'
    Password:
      type: string
      maxLength: 100
      description: 'Пароль'
      example: 'Qwerty123'
    Photo:
     type: string
     format: binary
     description: 'Картинка, закодированная в Base'
     example: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAgMAAABieywaAAAACVBMVEUAAAD///9fX1/S0ecCAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAACklEQVQImWNoAAAAggCByxOyYQAAAABJRU5ErkJggg=='
  
    User:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        surname:
          $ref: '#/components/schemas/Surname'
        phone:
          $ref: '#/components/schemas/Phone'
        email:
          $ref: '#/components/schemas/Email'
        photo:
          $ref: '#/components/schemas/Photo'
    
    CustomUserCreate:
      type: object
      properties:
        name:
          $ref: '#/components/schemas/Name'
        surname:
          $ref: '#/components/schemas/Surname'
        phone:
          $ref: '#/components/schemas/Surname'
        email:
          $ref: '#/components/schemas/Phone'
        password:
          $ref: '#/components/schemas/Password'
      required:
        - name
        - surname
        - phone
        - email
        - password
        
    CustomUserResponseOnCreate:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          $ref: '#/components/schemas/Name'
        surname:
          $ref: '#/components/schemas/Surname'
        email:
          $ref: '#/components/schemas/Email'
          
    TokenCreate:
      type: object
      properties:
        password:
          $ref: '#/components/schemas/Password'
        email:
          $ref: '#/components/schemas/Email'
      required:
        - email
        - password
    
    TokenGetResponse:
      type: object
      properties:
        auth_token:
          type: string
    
    TrainingType:
      type: string
      enum:
        - 'Бег'
        - 'Велосипед'
        - 'Ходьба'
      description: 'Тип тренировки'
      example: 'Бег'
    StartedAt:
      type: string
      format: '2023-07-04T00:05:23+03:00'
      description: 'Время начала тренировки'
      example: '2023-07-04T00:05:23+03:00'
    Duration:
      type: string
      format: '01:30'
      description: 'Длительность тренировки'
      example: '01:30'
    Rating:
      type: integer
      description: 'Рейтинг тренировки от 1 до 10'
      example: 1
    
    Training:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        training_type:
          $ref: '#/components/schemas/TrainingType'
        started_at:
          $ref: '#/components/schemas/StartedAt'
        duration:
          $ref: '#/components/schemas/Duration'
        rating:
          $ref: '#/components/schemas/Rating'
      required: 
        - id
        - training_type
        - started_at
    
    TrainingCreate:
      type: object
      properties:
        training_type:
          $ref: '#/components/schemas/TrainingType'
        started_at:
          $ref: '#/components/schemas/StartedAt'
        duration:
          $ref: '#/components/schemas/Duration'
      required: 
        - training_type
        - started_at
    
    ValidationError:
      description: Стандартные ошибки валидации DRF
      type: object
      properties:
        field_name:
          description: 'Название поля, в котором произошли ошибки. Таких полей может быть несколько'
          example: [ 'Обязательное поле.' ]
          type: array
          items:
            type: string
    
    ActivationError:
      description: Неверные ключ и токен
      type: object
      properties:
        uid:
          type: string
        token:
          type: string
          
    AuthenticationError:
      description: Пользователь не авторизован
      type: object
      properties:
        detail:
          description: 'Описание ошибки'
          example: 'Учетные данные не были предоставлены'
          type: string
          
    PermissionDenied:
      description: Недостаточно прав
      type: object
      properties:
        detail:
          description: 'Описание ошибки'
          example: 'У вас недостаточно прав для выполнения данного действия'
          type: string
    
    NotFound:
      description: Объект не найден
      type: object
      properties:
        detail:
          description: 'Описание ошибки'
          example: 'Объект не найден'
          type: string
    
            
  responses:

    ValidationError:
      description: 'Ошибки валидации в стандартном формате DRF'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    
    ActivationError:
      description: Неверные ключ и токен
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ActivationError'
    
    AuthenticationError:
      description: Пользователь не авторизован
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AuthenticationError'
            
    PermissionDenied:
      description: Недостаточно прав
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PermissionDenied'
    
    NotFound:
      description: Объект не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/NotFound'
            
  securitySchemes:
    Token:
      description: 'Авторизация по токену. <br>'
      type: http
      scheme: token